<?php

namespace App\carepays_providers;

use Illuminate\Database\Eloquent\Model;

class nucc_provider_details extends Model
{
    protected $table = 'npidata_20180610';
    protected $primaryKey = 'id';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'id',
        'npi',
        'entity_type_code',
        'replacement_npi',
        'employer_identification_number_ein',
        'provider_organization_name',
        'provider_last_name',
        'provider_first_name',
        'provider_middle_name',
        'provider_name_prefix_text',
        'provider_name_suffix_text',
        'provider_credential_text',
        'provider_other_org_name',
        'provider_other_org_name_type_code',
        'provider_other_last_name',
        'provider_other_first_name',
        'provider_other_middle_name',
        'provider_other_name_prefix_text',
        'provider_other_name_suffix_text',
        'provider_other_credential_text',
        'provider_other_last_name_type_code',
        'provider_first_line_business_mailing_address',
        'provider_second_line_business_mailing_address',
        'provider_business_mailing_address_city_name',
        'provider_business_mailing_address_state_name',
        'provider_business_mailing_address_postal_code',
        'provider_business_mailing_address_country_code',
        'provider_business_mailing_address_telephone_number',
        'provider_business_mailing_address_fax_number',
        'provider_first_fine_business_practice_location_address',
        'provider_second_line_business_practice_location_address',
        'provider_business_practice_location_address_city_name',
        'provider_business_practice_location_address_state_name',
        'provider_business_practice_location_address_postal_code',
        'provider_business_practice_location_address_country_code',
        'provider_business_practice_location_address_telephone_number',
        'provider_business_practice_location_address_fax_number',
        'provider_enumeration_date',
        'last_update_date',
        'npi_deactivation_reason_code',
        'npi_deactivation_date',
        'npi_reactivation_date',
        'provider_gender_code',
        'authorized_official_last_name',
        'authorized_official_first_name',
        'authorized_official_middle_name',
        'authorized_official_title_or_position',
        'authorized_official_telephone_number',
        'healthcare_provider_taxonomy_code_1',
        'provider_license_number_1',
        'provider_license_number_state_code_1',
        'healthcare_provider_primary_taxonomy_switch_1',
        'healthcare_provider_taxonomy_code_2',
        'provider_license_number_2',
        'provider_license_number_state_code_2',
        'healthcare_provider_primary_taxonomy_switch_2',
        'healthcare_provider_taxonomy_code_3',
        'provider_license_number_3',
        'provider_license_number_state_code_3',
        'healthcare_provider_primary_taxonomy_switch_3',
        'is_sole_proprietor',
        'is_organization_subpart',
        'parent_organization_lbn',
        'parent_organization_tin',
        'authorized_official_name_prefix_text',
        'authorized_official_name_suffix_text',
        'authorized_official_credential_text',
        'healthcare_provider_taxonomy_group_1',
        'healthcare_provider_taxonomy_group_2',
        'healthcare_provider_taxonomy_group_3',
        'healthcare_provider_taxonomy_group_4',
        'healthcare_provider_taxonomy_group_5',
        'healthcare_provider_taxonomy_group_6',
        'healthcare_provider_taxonomy_group_7',
        'healthcare_provider_taxonomy_group_8',
        'healthcare_provider_taxonomy_group_9',
        'healthcare_provider_taxonomy_group_10',
        'healthcare_provider_taxonomy_group_11',
        'healthcare_provider_taxonomy_group_12',
        'healthcare_provider_taxonomy_group_13',
        'healthcare_provider_taxonomy_group_14',
        'healthcare_provider_taxonomy_group_15'
    ];
}
