name: CI-PROD

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.x, 12.x]
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -t rsa -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   name: Use Node.js v14
      #   with:
      #     node-version: "14"
        # with:
        #   node-version: ${{ matrix.node-version }}
      # - name: yarn install
      #   run: yarn install
      # - name: yarn test
      #   run: |
      #     yarn test
      #   env:
      #     CI: true
      # - name: yarn build
      #   run: yarn generate --if-present
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.PROD_REMOTE_USER }}@${{ secrets.PROD_REMOTE_HOST }}:/var/www/apis.carepays.com --exclude=.git --exclude=storage
